### PR TITLE
Dimaga Beach ring fix

### PR DESCRIPTION
**Pull request by sevu**
main change:
there is a bug in Dimaga which allows the rings to be only picked up with a 50% chance.

more info in the commit messages.

PS: maybe link to the repo in the add-on description

### CODE REVIEW

**Review by trewe — COMMENTED** [review]
The Lich is consistently spelled as Mal-Daugur everywhere else, except once in this scenario though. (line #612)

**Review by trewe — COMMENTED** [review]
I rather change the message here, as the range was commented out for a reason

**Review by trewe — COMMENTED** [review]
are the terrain changes in 1.14 branch? the wmltools dont report anything suspicious.

**Comment by sevu** [comment]
updated the PR with the changes.

For terrain, a lot of new terrains has been added, mostly for Keeps, but also for caves, e.g. Mine Walls or Clean Walls.

For deprecated Terrain, I just remember the one in question. Usually, when existing terrain is deprecated, the old code continues to work, but the map editor doesn't offer to place it anymore.

Another changes was with the gate terrains – the old code was removed and directional variants (like with bridges) were added.

Oh, yeah, there's one more, not strictly a terrain change: The macro for fire camps is deprecated — it got it's own terrain now.

**Pull request merged**
